---
title: "dataExploration"
author: "North Carpenter"
date: "2/17/2022"
output: html_document
---

```{r}
library(ISLR)
library(dplyr)
library(readr)
library(broom)
library(ggplot2)
library(splines)
library(tidymodels)
tidymodels_prefer()
```


```{r}
COVID_State <- read_csv("/Users/NorthCarpenter/Documents/Sort/School/University Managment/Studdies/Third Year/Stats 253/Stat253 Project/EconomicTracker-main/data/COVID - State - Daily.csv")

Employment_State <- read_csv("/Users/NorthCarpenter/Documents/Sort/School/University Managment/Studdies/Third Year/Stats 253/Stat253 Project/EconomicTracker-main/data/Employment - State - Daily.csv")

Mobility_State <- read_csv("/Users/NorthCarpenter/Documents/Sort/School/University Managment/Studdies/Third Year/Stats 253/Stat253 Project/EconomicTracker-main/data/Google Mobility - State - Daily.csv")
  
Spending_State <- read_csv("/Users/NorthCarpenter/Documents/Sort/School/University Managment/Studdies/Third Year/Stats 253/Stat253 Project/EconomicTracker-main/data/Affinity - State - Daily.csv")
```
